name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install nasm
      run: sudo apt-get install nasm
    - name: make check
      run: make check
