name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install nasm; sudo apt-get install libpthread-stubs0-dev
    - name: configure python
      run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10; sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
    - name: make dir
      run: mkdir build
    - name: make check
      run: make check
